import express from 'express'; import cors from 'cors'; import bcrypt from 'bcryptjs'; import 'dotenv/config';
import { db } from './db.js'; import { authenticate, authorize, createToken } from './auth.js'; import { userRules, validate, isRealisticEmail } from './validation.js';
const app = express(); app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' })); app.use(express.json());
const roles = ['ADMIN','USER','OWNER']; const safeSort = (v, allowed, fallback) => allowed.includes(v) ? v : fallback; const order = v => v === 'asc' ? 'ASC' : 'DESC';

app.get('/api/health', (_,res) => res.json({ ok:true }));
app.post('/api/auth/register', userRules, validate, async (req,res,next) => { try { const {name,email,address,password}=req.body; const [exists]=await db.query('SELECT id FROM users WHERE email=?',[email]); if(exists.length) return res.status(409).json({message:'Email already registered.'}); const password_hash=await bcrypt.hash(password,12); const [r]=await db.query('INSERT INTO users(name,email,address,password_hash,role) VALUES(?,?,?,?,\'USER\')',[name,email,address,password_hash]); const user={id:r.insertId,name,email,address,role:'USER'}; res.status(201).json({token:createToken(user),user}); } catch(e){next(e)} });
app.post('/api/auth/login', async (req,res,next)=>{try { const email=String(req.body.email||'').toLowerCase(); if(!isRealisticEmail(email)) return res.status(422).json({message:'Email is invalid. Use a real address such as name@example.com.'}); const [rows]=await db.query('SELECT * FROM users WHERE email=? AND deleted_at IS NULL',[email]); const user=rows[0]; if(!user || !(await bcrypt.compare(req.body.password||'',user.password_hash))) return res.status(401).json({message:'Incorrect email or password.'}); res.json({token:createToken(user),user:{id:user.id,name:user.name,email:user.email,address:user.address,role:user.role}}); }catch(e){next(e)}});
app.post('/api/auth/forgot', async (req,res,next)=>{try { const email=String(req.body.email||''); if(!isRealisticEmail(email)) return res.status(422).json({message:'Email is invalid. Use a real address such as name@example.com.'}); const [rows]=await db.query('SELECT id FROM users WHERE email=?',[email.toLowerCase()]); if(!rows.length)return res.status(404).json({message:'No account found for that email.'}); await db.query('UPDATE users SET password_hash=? WHERE id=?',[await bcrypt.hash('Demo@123',12),rows[0].id]); res.json({message:'Password reset.'}); }catch(e){next(e)}});
app.get('/api/auth/me',authenticate,async(req,res,next)=>{try { const [r]=await db.query('SELECT id,name,email,address,role FROM users WHERE id=?',[req.user.id]); res.json(r[0]); }catch(e){next(e)}});
app.patch('/api/auth/password',authenticate,async(req,res,next)=>{try { const p=req.body.password||''; if(!/^.{8,16}$/.test(p)||!/[A-Z]/.test(p)||!/[^A-Za-z0-9]/.test(p)) return res.status(422).json({message:'Password must be 8–16 characters with an uppercase letter and special character.'}); await db.query('UPDATE users SET password_hash=? WHERE id=?',[await bcrypt.hash(p,12),req.user.id]);res.json({message:'Password updated.'});}catch(e){next(e)}});
app.delete('/api/auth/account',authenticate,authorize('USER'),async(req,res,next)=>{try { await db.query('DELETE FROM ratings WHERE user_id=?',[req.user.id]); await db.query('UPDATE users SET deleted_at=NOW() WHERE id=? AND role=\'USER\'',[req.user.id]); res.json({message:'Account deleted.'}); }catch(e){next(e)}});
app.get('/api/stores',authenticate,async(req,res,next)=>{try { const {search='',sort='name',dir='asc'}=req.query; const field=safeSort(sort,['name','email','address','average_rating'],'name'); const q = String(search || ''); const params=[`%${q}%`,`%${q}%`,`%${q}%`,`%${q}%`]; let extra=''; if(req.user.role==='USER'){extra=' , r.rating AS user_rating'; params.push(req.user.id)} const join=req.user.role==='USER'?'LEFT JOIN ratings r ON r.store_id=s.id AND r.user_id=?':''; const [rows]=await db.query(`SELECT s.id,s.name,s.email,s.address,s.owner_id,ROUND(AVG(rt.rating),1) average_rating,COUNT(rt.id) rating_count${extra} FROM stores s LEFT JOIN ratings rt ON rt.store_id=s.id ${join} WHERE s.deleted_at IS NULL AND (s.name LIKE ? OR s.address LIKE ? OR CAST(s.id AS CHAR) LIKE ? OR CAST(s.owner_id AS CHAR) LIKE ?) GROUP BY s.id ${req.user.role==='USER'?',r.rating':''} ORDER BY ${field} ${order(dir)}`,params);res.json(rows);}catch(e){next(e)}});
app.post('/api/stores/:id/rating',authenticate,authorize('USER'),async(req,res,next)=>{try {const rating=Number(req.body.rating); if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(422).json({message:'Rating must be a whole number from 1 to 5.'}); await db.query('INSERT INTO ratings(store_id,user_id,rating) VALUES(?,?,?) ON DUPLICATE KEY UPDATE rating=VALUES(rating)',[req.params.id,req.user.id,rating]);res.json({message:'Rating saved.'});}catch(e){next(e)}});
app.get('/api/admin/stats',authenticate,authorize('ADMIN'),async(req,res,next)=>{try{const [[stats]]=await db.query(`SELECT
  (SELECT COUNT(*) FROM users WHERE deleted_at IS NULL) users,
  (SELECT COUNT(*) FROM stores) stores,
  (SELECT COUNT(*) FROM ratings) ratings,
  (SELECT ROUND(AVG(rating),1) FROM ratings) average_rating,
  (SELECT COUNT(*) FROM users WHERE deleted_at IS NULL AND created_at >= DATE_FORMAT(CURDATE(), '%Y-%m-01')) users_this_month,
  (SELECT COUNT(*) FROM users WHERE deleted_at IS NULL AND created_at >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH), '%Y-%m-01') AND created_at < DATE_FORMAT(CURDATE(), '%Y-%m-01')) users_last_month,
  (SELECT COUNT(*) FROM stores WHERE deleted_at IS NULL AND created_at >= DATE_FORMAT(CURDATE(), '%Y-%m-01')) stores_this_month,
  (SELECT COUNT(*) FROM stores WHERE deleted_at IS NULL AND created_at >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH), '%Y-%m-01') AND created_at < DATE_FORMAT(CURDATE(), '%Y-%m-01')) stores_last_month,
  (SELECT COUNT(*) FROM ratings WHERE created_at >= DATE_FORMAT(CURDATE(), '%Y-%m-01')) ratings_this_month,
  (SELECT COUNT(*) FROM ratings WHERE created_at >= DATE_FORMAT(DATE_SUB(CURDATE(), INTERVAL 1 MONTH), '%Y-%m-01') AND created_at < DATE_FORMAT(CURDATE(), '%Y-%m-01')) ratings_last_month`);
  const [roleRows]=await db.query("SELECT role,COUNT(*) count FROM users WHERE deleted_at IS NULL GROUP BY role");
  const [ratingRows]=await db.query('SELECT rating,COUNT(*) count FROM ratings GROUP BY rating ORDER BY rating');
  const growth=(current,previous)=>previous ? Number((((current-previous)/previous)*100).toFixed(1)) : current ? 100 : 0;
  res.json({...stats,growth:{users:growth(stats.users_this_month,stats.users_last_month),stores:growth(stats.stores_this_month,stats.stores_last_month),ratings:growth(stats.ratings_this_month,stats.ratings_last_month)},roles:roleRows,ratingDistribution:ratingRows});
}catch(e){next(e)}});
app.get('/api/admin/users',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const {search='',role='',sort='name',dir='asc'}=req.query;const field=safeSort(sort,['name','email','address','role'],'name');const q=String(search||'');const [r]=await db.query(`SELECT id,name,email,address,role FROM users WHERE deleted_at IS NULL AND (name LIKE ? OR email LIKE ? OR address LIKE ? OR CAST(id AS CHAR) LIKE ?) AND role LIKE ? ORDER BY ${field} ${order(dir)}`,[`%${q}%`,`%${q}%`,`%${q}%`,`%${q}%`,`%${role}%`]);res.json(r)}catch(e){next(e)}});
app.get('/api/admin/past-users',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const [r]=await db.query('SELECT id,name,email,address,role,deleted_at FROM users WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC');res.json(r)}catch(e){next(e)}});
app.get('/api/admin/past-stores',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const [r]=await db.query('SELECT id,name,email,address,owner_id,deleted_at FROM stores WHERE deleted_at IS NOT NULL ORDER BY deleted_at DESC');res.json(r)}catch(e){next(e)}});
app.get('/api/admin/users/:id',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const [[r]]=await db.query(`SELECT u.id,u.name,u.email,u.address,u.role,ROUND(AVG(rt.rating),1) AS store_rating FROM users u LEFT JOIN stores s ON s.owner_id=u.id LEFT JOIN ratings rt ON rt.store_id=s.id WHERE u.id=? AND u.deleted_at IS NULL GROUP BY u.id`,[req.params.id]);if(!r)return res.status(404).json({message:'User not found.'});res.json(r)}catch(e){next(e)}});
app.post('/api/admin/users',authenticate,authorize('ADMIN'),userRules,validate,async(req,res,next)=>{try{const {name,email,address,password,role='USER'}=req.body;if(!roles.includes(role))return res.status(422).json({message:'Invalid role.'});const [exists]=await db.query('SELECT id FROM users WHERE email=?',[email]);if(exists.length)return res.status(409).json({message:'Email already registered.'});await db.query('INSERT INTO users(name,email,address,password_hash,role) VALUES(?,?,?,?,?)',[name,email,address,await bcrypt.hash(password,12),role]);res.status(201).json({message:'User created.'})}catch(e){next(e)}});
app.post('/api/admin/stores',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const {name,email,address,ownerId=null}=req.body;if(!name?.trim()||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email||'')||!address?.trim())return res.status(422).json({message:'Store name, valid email and address are required.'});await db.query('INSERT INTO stores(name,email,address,owner_id) VALUES(?,?,?,?)',[name.trim(),email.trim(),address.trim(),ownerId||null]);res.status(201).json({message:'Store created.'});}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({message:'Store email or owner already assigned.'});next(e)}});
app.patch('/api/admin/stores/:id/owner',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const ownerId = req.body.ownerId === '' || req.body.ownerId == null ? null : Number(req.body.ownerId); const [result]=await db.query('UPDATE stores SET owner_id=? WHERE id=? AND deleted_at IS NULL',[ownerId, req.params.id]); if(!result.affectedRows) return res.status(404).json({message:'Store not found.'}); res.json({message:'Store owner updated.'}); } catch(e){ next(e); } });
app.delete('/api/admin/stores/:id',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const [result]=await db.query('UPDATE stores SET deleted_at=NOW() WHERE id=? AND deleted_at IS NULL',[req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'Store not found.'});res.json({message:'Store moved to archive.'});}catch(e){next(e)}});
app.delete('/api/admin/users/:id',authenticate,authorize('ADMIN'),async(req,res,next)=>{try {const [result]=await db.query('UPDATE users SET deleted_at=NOW() WHERE id=? AND deleted_at IS NULL',[req.params.id]);if(!result.affectedRows)return res.status(404).json({message:'User not found.'});res.json({message:'User moved to archive.'});}catch(e){next(e)}});
app.get('/api/owner/dashboard',authenticate,authorize('OWNER'),async(req,res,next)=>{try{const [[summary]]=await db.query('SELECT s.id,s.name,s.address,ROUND(AVG(r.rating),1) average_rating,COUNT(r.id) rating_count,MAX(r.rating) highest_rating,MIN(r.rating) lowest_rating FROM stores s LEFT JOIN ratings r ON r.store_id=s.id WHERE s.owner_id=? AND s.deleted_at IS NULL GROUP BY s.id',[req.user.id]);if(!summary)return res.status(404).json({message:'No store assigned to this owner.'});const [raters]=await db.query('SELECT u.name,u.email,u.address,r.rating,r.updated_at FROM ratings r JOIN users u ON u.id=r.user_id WHERE r.store_id=? ORDER BY r.updated_at DESC',[summary.id]);res.json({summary,raters});}catch(e){next(e)}});
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({message:'Something went wrong.'})});
async function ensureUserArchiveColumn(){const [[column]]=await db.query("SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='users' AND column_name='deleted_at'");if(!column)await db.query('ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL, ADD INDEX idx_users_deleted (deleted_at)');}
async function ensureStoreArchiveColumn(){const [[column]]=await db.query("SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='stores' AND column_name='deleted_at'");if(!column)await db.query('ALTER TABLE stores ADD COLUMN deleted_at TIMESTAMP NULL DEFAULT NULL, ADD INDEX idx_stores_deleted (deleted_at)');}
Promise.all([ensureUserArchiveColumn(), ensureStoreArchiveColumn()]).then(()=>app.listen(process.env.PORT||4000,()=>console.log('API listening on 4000'))).catch(error=>{console.error('Database migration failed.',error);process.exit(1)});
